output-format: text

strictness: veryhigh
test-warnings: true
doc-warnings: false
member-warnings: true

uses:
  - django

pep8:
  full: true
  disable:
    - D100
    - D101
    - D102
    - D103
    - D105
    - D205
    - D400
    - N802
  options:
    max-line-length: 100

pyflakes:
  disable:
    - F401
    - F999

pylint:
  disable:
    - too-few-public-methods
    - invalid-name
    - no-self-use
    - no-member
    - too-many-ancestors
    - wrong-import-order
  options:
    max-line-length: 100

dodgy:
  run: true

ignore-paths:
  - venv
  - env
  - .env
  - .venv

ignore-patterns:
  - .+/migrations/.+
  - .+/settings/.+
